### ISSUE TITLE
Usage of SEM2D2.3.8

### ISSUE THREAD

**Issue by VGKrishna** [jpampuero/sem2dpack#4]
I am trying to use the SEM2DPACK2.3.8 for modeling a 2D layered crustal model (inferred from Controlled Seismic Studies) attached herewith. I intend to generate the vertical component seismograms for a few source positions about 40 km apart and out to a  maximum range of about 180 km from the source, and the seismograms are to be generated at smaller intervals of less than or equal to about 0.5 km trying plausible density and Qp and Qs values besides Vp and Vs in different layers. I request for kind help to make a starting input data file including that for the necessary mesh generation as well.
I have installed the package on a Windows computer with the aid of the CYGWIN64 and could also run some of the given examples there. However for the given 2-D crustal model I request kindly to help me for a starting input data file that I may be able to use for different iterations as may be needed.

**Comment by jpampuero** [comment]
Your question is too open-ended for us to provide any help efficiently. Can you be more specific?
If you are looking for an example with attenuation, have a look at EXAMPLES/Attenuation/
