### ISSUE TITLE
bc_dynflt_rsf.f90:339:78: "Error: Symbol ‘it’ at (1) has no IMPLICIT type; did you mean ‘i’?"

### ISSUE THREAD

**Issue by Aangniu** [jpampuero/sem2dpack#7]
Dear developers,

Thanks for your time! I am recently trying to compile from the source code on the main branch. However, the following errors are reported:

```
bc_dynflt_rsf.f90:339:78:

  339 |        v(i)=nr_solver(nr_fric_func_tau,estimateLow,estimateHigh,tolerance,f,it,theta(i),tau_stick(i),sigma(i),Z(i))
      |                                                                              1
Error: Symbol ‘it’ at (1) has no IMPLICIT type; did you mean ‘i’?
make: *** [Makefile:90: bc_dynflt_rsf.o] Error 1
```

How may I fix this problem? I am using the GNU toolchain for compilation.

Thanks in advance :)

**Comment by jpampuero** [comment]
It should be "i" instead of "it". I introduced this bug in the commit of January 6 2013, sorry about that. I fixed it in the main branch now.

**Comment by adarshdevd** [comment]
Dear developers,

Thanks for your time! I am recently trying to compile from the source code on the main branch. However, the following errors are reported:

##################################
```
ifort -O3 -c bc_dynflt_rsf.f90
bc_dynflt_rsf.f90(286): error #6404: This name does not have a type, and must have an explicit type.   [IT]
      where (theta_new < 1.0d-12) theta_new(it) = 0d0
--------------------------------------------^
bc_dynflt_rsf.f90(286): error #6087: An array assignment statement is required in this context.   [THETA_NEW]
      where (theta_new < 1.0d-12) theta_new(it) = 0d0
----------------------------------^
compilation aborted for bc_dynflt_rsf.f90 (code 1)
make: *** [Makefile:90: bc_dynflt_rsf.o] Error 1 
```
############################################

please help me to solve this compilation error.

**Comment by adarshdevd** [comment]
Dear developers,

Thanks for your time! I am recently trying to compile from the source code on the main branch. However, the following errors are reported:

##################################
```
 ifort -O3 -c bc_dynflt_rsf.f90
bc_dynflt_rsf.f90(286): error #6404: This name does not have a type, and must have an explicit type.   [IT]
      where (theta_new < 1.0d-12) theta_new(it) = 0d0
--------------------------------------------^
bc_dynflt_rsf.f90(286): error #6087: An array assignment statement is required in this context.   [THETA_NEW]
      where (theta_new < 1.0d-12) theta_new(it) = 0d0
----------------------------------^
compilation aborted for bc_dynflt_rsf.f90 (code 1)
make: *** [Makefile:90: bc_dynflt_rsf.o] Error 1 

```
############################################




I change it to 'i' still I am getting following error :




#####################
ifort -O3 -c bc_dynflt_rsf.f90
bc_dynflt_rsf.f90(286): error #6404: This name does not have a type, and must have an explicit type.   [I]
      where (theta_new < 1.0d-12) theta_new(i) = 0d0
--------------------------------------------^
bc_dynflt_rsf.f90(286): error #6087: An array assignment statement is required in this context.   [THETA_NEW]
      where (theta_new < 1.0d-12) theta_new(i) = 0d0
----------------------------------^
compilation aborted for bc_dynflt_rsf.f90 (code 1)
make: *** [Makefile:90: bc_dynflt_rsf.o] Error 1

#######################################


please help me to solve this compilation error.

**Comment by jpampuero** [comment]
My bad, I introduced a typo on January 9. I fixed it now.
P

**Comment by adarshdevd** [comment]
Thanks
